services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dolidb}
      MYSQL_USER: ${MYSQL_USER:-dolidbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dolidbpass}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  db_data:


